server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test20230117?serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.rxee.server.entity
  #configuration:
   # map-underscore-to-camel-case: false

logging:
  level:
    com.rxee.server.mapper: debug
