spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test20230117?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
#    host: 112.74.82.69
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
    timeout: 10000
    #password: 123456
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rxee.backend.entity
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

